FROM jenkins/jenkins:2.235.2-lts-centos7

ENV JENKINS_USER {{ jenkins_user }}
ENV JENKINS_PASS {{ jenkins_pass }}
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
# ENV CASC_JENKINS_CONFIG /var/jenkins_home/casc_configs/jenkins.yaml

# install jenkins plugins
COPY ./jenkins-plugins /usr/share/jenkins/jenkins-plugins

RUN while read i ; \
      do /usr/local/bin/install-plugins.sh $i ; \
    done < /usr/share/jenkins/jenkins-plugins

RUN /usr/local/bin/plugins.sh /usr/share/jenkins/jenkins-plugins

COPY ./scripts/. /usr/share/jenkins/ref/init.groovy.d/

# COPY ./jenkins.yaml /var/jenkins_home/casc_configs/
VOLUME /var/jenkins_home
